### ISSUE TITLE
2.0.0 version issue

### ISSUE THREAD

**Issue by Sagez** [Oceanel51/Food-Industry#11]
Via on 2.0.0 version, there is issue with animation speed with fi-greenhouse that need to be same to hr_version and need rename apple-seeding.png and orange-seedling.png to lower case due to linux.. anyway. hope this helps for anyone who want use 2.0.0 version.

Build version 2.0.0 downloaded at Feb. 20, 2019

**Comment by Oceanel51** [comment]
Thanks for report, everything has been fixed.
