### ISSUE TITLE
Fill the flask by click on "pure-water" resource entity

### ISSUE THREAD

**Issue by Oceanel51** [Oceanel51/Food-Industry#7]
What needs to be the result:
- we take in the cursor a stack of empty flasks (for example in the picture there are two)
- click on the resource "pure-water" (which in the amount of 20500)
- after clicking we get the full flask in inventory, and the empty one is removed
- since one flask has a stock of 30, then after filling two flasks, the availability of the resource should decrease by 60
**Total**: 2 full flasks and amount of pure-water 20440.

![2019-02-15_234344](https://user-images.githubusercontent.com/19427757/52885971-8f835c80-317b-11e9-904a-db4663d23fb8.png)

**Comment by jonkeda** [comment]
hi, I have this working. Also working for glass and plastic bottles. Could you give me rights to this branch?

**Comment by Oceanel51** [comment]
> Could you give me rights to this branch?
>
Of course, what should I do to make it right?

> I have this working. Also working for glass and plastic bottles.
>
it is very necessary to fill the flask, because the pumpjack is not available at the beginning of the game. Thanks!
Plastic bottles do not need to do this, because when it becomes possible to make plastic, technologies for working with liquids will already be studied and no one will fill plastic bottles by hand.
For glass is similar, besides sprites are not ready for them.

**Comment by Oceanel51** [comment]
Also need to fix this, because I do not know how:

1. One cattle should spawn from one minute to six, random. At the moment it is very often.
2. Using fruit scissors you can collect from 5 to 20 units, then the tree should destroy (like when you press right click). But it would be cool for different trees its range. Is it possible?
3. Is it possible to make scissors usable, like example, iron axe?
![2019-02-15_231633](https://user-images.githubusercontent.com/19427757/52884811-c8b9cd80-3177-11e9-9d57-eabd6d360d40.png)
4. Increase the growth rate of trees from seedlings, 10 sec is very fast, need randomly from 30 seconds to 2 minutes.
5. And for some reason, apple seeds and orange are endless, even in a regular game.

Thanks!

**Comment by jonkeda** [comment]
Could you give "jonkeda" rights? Github now wants to give @jonkeda rights. And that doesn't seem to work. Silly github.

my email is jonkeda@hotmail.com if you want to communicate without github.

**Comment by jonkeda** [comment]
> Also need to fix this, because I do not know how:
> 1. One cattle should spawn from one minute to six, random. At the moment it is very often.
> 
 1. I changed the spawn_cooldown in the cattlespawner

> 2. Using fruit scissors you can collect from 5 to 20 units, then the tree should destroy (like when you press right click). But it would be cool for different trees its range. Is it possible?

2. I'll try

> 3. Is it possible to make scissors usable, like example, iron axe?
>    ![2019-02-15_231633](https://user-images.githubusercontent.com/19427757/52884811-c8b9cd80-3177-11e9-9d57-eabd6d360d40.png)


> 4. Increase the growth rate of trees from seedlings, 10 sec is very fast, need randomly from 30 seconds to 2 minutes.

> 5. And for some reason, apple seeds and orange are endless, even in a regular game.

5. Fixed this

> 
> Thanks!

**Comment by Oceanel51** [comment]
Added you to the collaborators, accept the request, I don’t know how else :))). This is my first github and git experience.

**Comment by Oceanel51** [comment]
broke the click after 0.17
![2019-03-04_231926](https://user-images.githubusercontent.com/19427757/53802849-8e0fad80-3f4b-11e9-930e-8f10086fb08d.png)

**Comment by Oceanel51** [comment]
Also need to reduce the amount of resource on the pure-water entity when clicked. Is it possible to?

**Comment by Oceanel51** [comment]
Fixed and done.
